version: "3"
services:
  app1:
    build: .
    command: sample/default/rel/sample_app/bin/sample_app foreground
    environment:
      - RELX_REPLACE_OS_VARS=true
      - EPMDLESS_DIST_PORT=17012
      - NODE_NAME=app1@10.68.206.60
      - COOKIE=cookie
    ports:
      - 17012:17012

  app2:
    build: .
    command: sample/default/rel/sample_app/bin/sample_app foreground
    environment:
      - RELX_REPLACE_OS_VARS=true
      - EPMDLESS_DIST_PORT=17013
      - NODE_NAME=app2@10.68.206.60
      - COOKIE=cookie
    ports:
      - 17013:17013

  app3:
    build: .
    # Just to be able to connect to the node
    command: erl -noinput
    environment:
      - RELX_REPLACE_OS_VARS=true
      - EPMDLESS_DIST_PORT=17014
      - NODE_NAME=app3@10.68.206.60
      - COOKIE=cookie
    ports:
      - 17014:17014

